# Site settings
title: Nalssing blog
email: wnsgh2722@gmail.com
desc: 날씽의 프로그래밍 블로그입니다
description: > # this means to ignore newlines until "baseurl:"
  날씽 프로그래밍 블로그 루비 레일즈
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grandmarnier.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
