# Site settings
title: Nalssing Blog
desc: 날씽의 프로그래밍 블로그입니다
email: wnsgh2722@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grandmarnier.github.io" # the base hostname & protocol for your site
twitter_username: nalssing
github_username:  nalssing

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
