# Site settings
title: Nalssing Blog
desc: 날씽의 프로그래밍 블로그입니다
email: wnsgh2722@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grandmarnier.github.io" # the base hostname & protocol for your site
twitter_username: nalssing
github_username:  nalssing

# Build settings
markdown: kramdown
encoding: utf-8
